version: "3.9"

services:

  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    restart: always
    environment:
      ACCEPT_EULA: Y
      MSSQL_SA_PASSWORD: test@123
    volumes:
      - sqlvolume:/var/opt/mssql
    ports:
      - 1433:1433
    networks:
      - dnp

volumes:
    sqlvolume:

networks:
  dnp:
    name: dnp-network      
