# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: DEV

on:
  push:
    branches:
        - "main"
        - "feat/*" 
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 9.0.x

    - name: Restore dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --no-restore

    - name: Test by Testing.Platform .NET 9 & xUnit.v3 for MsSQL
      run: dotnet run --no-build --verbosity quiet --project src/Services/PeopleService/DNP.PeopleService.Tests.xUnitV3

    - uses: extractions/setup-just@v2
      with:
        just-version: 1.5.0  # optional semver specification, otherwise latest

    - name: Run Justfile
      run: just --justfile .justfile ms-test